# Generated by Django 2.2.2 on 2019-08-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imgae',
            new_name='image',
        ),
    ]
